version: '3.8'

services:

  app:
    container_name: ohlc_api
    build: 
      context: ./project
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - ./project:/app
    depends_on:
     - ohlc_postgres_db
    networks:
      - ohlc_net

  ohlc_postgres_db:
    image: postgres:latest
    container_name: ohlc_postgres_db
    restart: unless-stopped
    env_file:
      - .env 
    ports:
      - "5432:5432"
    expose:
      - 5432
    volumes:
      - ./psql_data:/var/lib/postgresql/data
    networks:
      - ohlc_net

volumes:
  psql_data:

networks:
  ohlc_net:
    driver: bridge

